# -*- coding: utf-8 -*-
"""group05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18U3RNw_rrhqyv70DRttum-1s1YfPNQlE
"""

# pyright: reportUndefinedVariable=false
from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
import math
import random
import time
camera_pos = (0, 500, 500)
fovY = 90
GRID_LENGTH = 600
rand_var = 423
quadric = None
_started = False
# Maze config
MAZE_N =5
CELL = 150
WALL_H = 120
WALL_T = 12
EYE_Z = 60
PLAYER_R = 22
PLAYER_SPEED = 18.0
TURN_STEP = 6
TOTAL_KEYS = 3
TIME_LIMIT = 150.0

# Combat config
PLAYER_FIRE_RATE = 0.25
BULLET_SPEED = 900.0
BULLET_LIFE = 1.3
SOLDIER_MOVE_SPEED = 45.0
SOLDIER_DETECT_RANGE = 350.0
SOLDIER_MELEE_RANGE = 30.0
GRENADE_FLIGHT_TIME = 0.9
GRENADE_FUSE = 1.6
GRENADE_RADIUS = 85.0
GRENADE_DAMAGE = 25.0
SOLDIER_CFG = {
    'pistol':  {'hp': 1, 'damage': 4,  'fire_rate': 1.8, 'color': (0.30, 0.28, 0.27), 'score': 40},
    'assault': {'hp': 3, 'damage': 6,  'fire_rate': 0.6, 'color': (0.28, 0.34, 0.24), 'score': 90},
    'shotgun': {'hp': 2, 'damage': 4,  'fire_rate': 2.0, 'color': (0.18, 0.14, 0.11), 'score': 70},
}
NUM_PISTOL = max(3, MAZE_N)
NUM_ASSAULT = max(2, MAZE_N // 2)
NUM_SHOTGUN = max(1, MAZE_N // 3)

#Game state
maze_grid = {}
wall_list = []
wall_boxes = []
player_x, player_y = 0.0, 0.0
player_angle = 45.0
player_health = 150.0
god_mode = False
hit_cooldown = 0.0
camera_mode = 'FPV'            # 'FPV' or 'TOP'
gems = []
keys_list = []
soldiers = []
bullets = []
grenades = []
explosions = []
pendulums = []
lasers = []
spikes = []
player_fire_cooldown = 0.0
door_open = False
door_x, door_y = 0.0, 0.0
door_box = None
gems_collected = 0
keys_collected = 0
score = 0
combo_count = 0
combo_timer = 0.0
COMBO_WINDOW = 3.0

time_left = TIME_LIMIT
game_state = 'playing'
last_tick = None
last_move_time = -10.0
elapsed_time = 0.0
danger_flash = False

#  TEXT DRAWING
def draw_text(x, y, text, font=GLUT_BITMAP_HELVETICA_18):
    glColor3f(1, 1, 1)
    glMatrixMode(GL_PROJECTION)
    glPushMatrix()
    glLoadIdentity()
    gluOrtho2D(0, 1000, 0, 800)
    glMatrixMode(GL_MODELVIEW)
    glPushMatrix()
    glLoadIdentity()

    glRasterPos2f(x, y)
    for ch in text:
        glutBitmapCharacter(font, ord(ch))
    glPopMatrix()
    glMatrixMode(GL_PROJECTION)
    glPopMatrix()
    glMatrixMode(GL_MODELVIEW)

#  MAZE GENERATION
def generate_maze(n):
    grid = {}
    for x in range(n):
        for y in range(n):
            grid[(x, y)] = {'N': True, 'S': True, 'E': True, 'W': True, 'visited': False}

    opp = {'N': 'S', 'S': 'N', 'E': 'W', 'W': 'E'}
    stack = [(0, 0)]
    grid[(0, 0)]['visited'] = True
    while stack:
        cx, cy = stack[-1]
        neighbours = []
        if cy > 0 and not grid[(cx, cy - 1)]['visited']:
            neighbours.append((cx, cy - 1, 'N'))
        if cy < n - 1 and not grid[(cx, cy + 1)]['visited']:
            neighbours.append((cx, cy + 1, 'S'))
        if cx > 0 and not grid[(cx - 1, cy)]['visited']:
            neighbours.append((cx - 1, cy, 'W'))
        if cx < n - 1 and not grid[(cx + 1, cy)]['visited']:
            neighbours.append((cx + 1, cy, 'E'))
        if not neighbours:
            stack.pop()
            continue
        nx, ny, d = random.choice(neighbours)
        grid[(cx, cy)][d] = False
        grid[(nx, ny)][opp[d]] = False
        grid[(nx, ny)]['visited'] = True
        stack.append((nx, ny))
    return grid
def cell_center(cx, cy):
    return cx * CELL, cy * CELL
def open_dirs(cx, cy):
    c = maze_grid[(cx, cy)]
    dirs = []
    if not c['N']: dirs.append('N')
    if not c['S']: dirs.append('S')
    if not c['E']: dirs.append('E')
    if not c['W']: dirs.append('W')
    return dirs
def cell_dist(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

def build_walls():
    global wall_list, wall_boxes
    wall_list = []
    wall_boxes = []
    n = MAZE_N
    for x in range(n):
        for y in range(n):
            c = maze_grid[(x, y)]
            if c['N']:
                wall_list.append((x * CELL, y * CELL - CELL / 2.0, 'X'))
            if c['W']:
                wall_list.append((x * CELL - CELL / 2.0, y * CELL, 'Y'))
            if y == n - 1 and c['S']:
                if x == n - 1:
                    continue
                wall_list.append((x * CELL, y * CELL + CELL / 2.0, 'X'))
            if x == n - 1 and c['E']:
                wall_list.append((x * CELL + CELL / 2.0, y * CELL, 'Y'))

    for (wx, wy, axis) in wall_list:
        if axis == 'X':
            wall_boxes.append((wx - (CELL + WALL_T) / 2.0, wx + (CELL + WALL_T) / 2.0,
                                wy - WALL_T / 2.0, wy + WALL_T / 2.0))
        else:
            wall_boxes.append((wx - WALL_T / 2.0, wx + WALL_T / 2.0,
                                wy - (CELL + WALL_T) / 2.0, wy + (CELL + WALL_T) / 2.0))


#  POPULATION
def pick_unique(pool, count):
    pool = list(pool)
    random.shuffle(pool)
    return pool[:count]
def make_patrol_path(cx, cy, steps=4):
    path = [cell_center(cx, cy)]
    cur = (cx, cy)
    for _ in range(steps):
        d = open_dirs(cur[0], cur[1])
        if not d: break
        choice = random.choice(d)
        nx, ny = cur
        if choice == 'N': ny -= 1
        elif choice == 'S': ny += 1
        elif choice == 'E': nx += 1
        elif choice == 'W': nx -= 1
        if not (0 <= nx < MAZE_N and 0 <= ny < MAZE_N): break
        cur = (nx, ny)
        path.append(cell_center(nx, ny))
    return path
def make_soldier(cx, cy, stype):
    wx, wy = cell_center(cx, cy)
    cfg = SOLDIER_CFG[stype]
    return {
        'x': wx, 'y': wy, 'type': stype,
        'hp': cfg['hp'], 'max_hp': cfg['hp'],
        'path': make_patrol_path(cx, cy), 'idx': 0,
        'state': 'patrol', 'facing': random.uniform(0, 360),
        'fire_timer': random.uniform(0.4, cfg['fire_rate']),
        'shots_fired': 0,
        'strafe_dir': random.choice([-1, 1]),
        'strafe_timer': random.uniform(0.5, 1.5),
        'detect_timer': random.uniform(0.0, 0.25),
        'alive': True,
        'hit_flash': 0.0,
    }
def populate_world():
    global gems, keys_list, soldiers, pendulums, lasers, spikes
    global door_x, door_y, door_box

    n = MAZE_N
    start = (0, 0)
    exit_cell = (n - 1, n - 1)
    all_cells = [(x, y) for x in range(n) for y in range(n)]
    far_cells = [c for c in all_cells if cell_dist(c, start) >= 3 and cell_dist(c, exit_cell) >= 1]
    used = set()
    def take(pool, count):
        available = [c for c in pool if c not in used]
        chosen = pick_unique(available, count)
        used.update(chosen)
        return chosen

    gem_cells = take(far_cells, 10)
    gems = [{'x': cell_center(cx, cy)[0], 'y': cell_center(cx, cy)[1], 'alive': True} for (cx, cy) in gem_cells]
    key_cells = take(far_cells, TOTAL_KEYS)
    key_colors = [(0.30, 0.93, 0.92), (1.0, 0.82, 0.25), (1.0, 0.18, 0.39)]
    keys_list = [{'x': cell_center(cx, cy)[0], 'y': cell_center(cx, cy)[1], 'alive': True, 'color': key_colors[i], 'index': i} for i, (cx, cy) in enumerate(key_cells)]
    def straight_cells(pool):
        out = []
        for c in pool:
            d = open_dirs(c[0], c[1])
            if ('N' in d and 'S' in d) or ('E' in d and 'W' in d):
                out.append(c)
        return out
    pend_cells = take(straight_cells(far_cells), 2)
    pendulums = [{'x': cell_center(cx, cy)[0], 'y': cell_center(cx, cy)[1], 'horiz': 'E' in open_dirs(cx, cy) and 'W' in open_dirs(cx, cy), 'phase': random.uniform(0, 6.28)} for (cx, cy) in pend_cells]
    laser_cells = take(straight_cells(far_cells), 3)
    lasers = [{'x': cell_center(cx, cy)[0], 'y': cell_center(cx, cy)[1], 'horiz': 'E' in open_dirs(cx, cy) and 'W' in open_dirs(cx, cy), 'length': CELL - 30, 'on': False, 'timer': random.uniform(0, 1.5), 'on_duration': 0.9, 'off_duration': 2.6} for (cx, cy) in laser_cells]

    spike_cells = take(far_cells, 4)
    spikes = [{'x': cell_center(cx, cy)[0], 'y': cell_center(cx, cy)[1], 'state': 'idle', 'timer': 0.0} for (cx, cy) in spike_cells]

    total_soldiers_needed = NUM_PISTOL + NUM_ASSAULT + NUM_SHOTGUN
    soldier_candidates = [c for c in all_cells if cell_dist(c, start) >= 2 and c not in used]
    soldier_cells = pick_unique(soldier_candidates, total_soldiers_needed)
    used.update(soldier_cells)
    soldiers = []
    for i, (cx, cy) in enumerate(soldier_cells):
        stype = 'pistol' if i < NUM_PISTOL else ('assault' if i < NUM_PISTOL + NUM_ASSAULT else 'shotgun')
        soldiers.append(make_soldier(cx, cy, stype))
    door_x = (n - 1) * CELL
    door_y = (n - 1) * CELL + CELL / 2.0
    door_box = (door_x - (CELL - 20) / 2.0, door_x + (CELL - 20) / 2.0, door_y - WALL_T / 2.0, door_y + WALL_T / 2.0)

#  GAME INIT
def init_game():
    global maze_grid, player_x, player_y, player_angle, player_health
    global god_mode, hit_cooldown, camera_mode, gems_collected, keys_collected
    global score, combo_count, combo_timer, time_left, game_state, door_open
    global last_tick, elapsed_time, bullets, grenades, explosions, player_fire_cooldown
    maze_grid = generate_maze(MAZE_N)
    build_walls()
    populate_world()
    player_x, player_y = cell_center(0, 0)
    player_angle = 45.0
    player_health = 150.0
    god_mode = False
    hit_cooldown = 0.0
    camera_mode = 'FPV'

    bullets = []
    grenades = []
    explosions = []
    player_fire_cooldown = 0.0
    gems_collected = 0
    keys_collected = 0
    score = 0
    combo_count = 0
    combo_timer = 0.0

    time_left = TIME_LIMIT
    game_state = 'playing'
    door_open = False

    last_tick = time.time()
    elapsed_time = 0.0
#  COLLISION HELPERS
def resolve_entity_collision(x, y, radius):
    for (minx, maxx, miny, maxy) in wall_boxes:
        cx = max(minx, min(x, maxx))
        cy = max(miny, min(y, maxy))
        dx, dy = x - cx, y - cy
        dist_sq = dx * dx + dy * dy
        if dist_sq < radius * radius:
            dist = math.sqrt(dist_sq) if dist_sq > 0.0001 else 0.0001
            push = radius - dist
            x += (dx / dist) * push
            y += (dy / dist) * push
    if door_box is not None and not door_open:
        minx, maxx, miny, maxy = door_box
        cx = max(minx, min(x, maxx))
        cy = max(miny, min(y, maxy))
        dx, dy = x - cx, y - cy
        dist_sq = dx * dx + dy * dy
        if dist_sq < radius * radius:
            dist = math.sqrt(dist_sq) if dist_sq > 0.0001 else 0.0001
            push = radius - dist
            x += (dx / dist) * push
            y += (dy / dist) * push
    return x, y

def resolve_collision(x, y):
    if god_mode:
        return x, y
    return resolve_entity_collision(x, y, PLAYER_R)
def has_line_of_sight(x1, y1, x2, y2, samples=6):
    for i in range(1, samples):
        t = i / float(samples)
        px = x1 + (x2 - x1) * t
        py = y1 + (y2 - y1) * t
        for (minx, maxx, miny, maxy) in wall_boxes:
            if minx <= px <= maxx and miny <= py <= maxy:
                return False
    return True
def circle_hit(px, py, hx, hy, r):
    dx, dy = px - hx, py - hy
    return (dx * dx + dy * dy) < r * r
def damage_player(amount):
    global player_health, hit_cooldown, game_state
    if god_mode or game_state != 'playing':
        return
    if hit_cooldown > 0:
        return
    player_health -= amount
    hit_cooldown = 0.8
    if player_health <= 0:
        player_health = 0
        game_state = 'lost'

#  DRAWING SHAPES
def draw_floor_and_ceiling():
    n = MAZE_N
    minx, maxx = -CELL, (n - 1) * CELL + CELL
    miny, maxy = -CELL, (n - 1) * CELL + CELL

    glColor3f(0.42, 0.68, 0.32)
    glBegin(GL_QUADS)
    glVertex3f(minx, miny, 0)
    glVertex3f(maxx, miny, 0)
    glVertex3f(maxx, maxy, 0)
    glVertex3f(minx, maxy, 0)
    glEnd()

    glColor3f(0.28, 0.52, 0.22)
    glBegin(GL_LINES)
    x = minx
    while x <= maxx:
        glVertex3f(x, miny, 0.5)
        glVertex3f(x, maxy, 0.5)
        x += CELL
    y = miny
    while y <= maxy:
        glVertex3f(minx, y, 0.5)
        glVertex3f(maxx, y, 0.5)
        y += CELL
    glEnd()
    if camera_mode != 'TOP':
        glColor3f(0.65, 0.85, 0.96)
        glBegin(GL_QUADS)
        glVertex3f(minx, miny, WALL_H)
        glVertex3f(maxx, miny, WALL_H)
        glVertex3f(maxx, maxy, WALL_H)
        glVertex3f(minx, maxy, WALL_H)
        glEnd()

def draw_walls():
    for i, (wx, wy, axis) in enumerate(wall_list):
        if (i + int(wx) + int(wy)) % 3 == 0:
            glColor3f(0.24, 0.52, 0.22)
        else:
            glColor3f(0.18, 0.42, 0.18)
        glPushMatrix()
        glTranslatef(wx, wy, WALL_H / 2.0)
        if axis == 'X':
            glScalef(CELL + WALL_T, WALL_T, WALL_H)
        else:
            glScalef(WALL_T, CELL + WALL_T, WALL_H)
        glutSolidCube(1.0)
        glPopMatrix()
def draw_door():
    glPushMatrix()
    glTranslatef(door_x, door_y, WALL_H / 2.0 + (WALL_H * 0.7 if door_open else 0))
    if door_open:
        glColor3f(0.03, 0.85, 0.65)
    else:
        glColor3f(0.85, 0.10, 0.25)
    glScalef(CELL - 20, WALL_T * 1.6, WALL_H)
    glutSolidCube(1.0)
    glPopMatrix()
def draw_gems():
    spin = (elapsed_time * 140.0) % 360.0
    bob = math.sin(elapsed_time * 2.2) * 8.0
    glColor3f(0.30, 0.93, 0.92)
    for g in gems:
        if not g['alive']: continue
        glPushMatrix()
        glTranslatef(g['x'], g['y'], 45 + bob)
        glRotatef(spin, 0, 0, 1)
        glRotatef(35, 1, 0, 0)
        glScalef(16, 16, 16)
        glutSolidOctahedron()
        glPopMatrix()

def draw_keys():
    spin = (elapsed_time * 90.0) % 360.0
    bob = math.sin(elapsed_time * 2.0) * 6.0
    for k in keys_list:
        if not k['alive']: continue
        glColor3f(*k['color'])
        glPushMatrix()
        glTranslatef(k['x'], k['y'], 45 + bob)
        glRotatef(spin, 0, 0, 1)
        glutSolidTorus(4.0, 12.0, 10, 18)
        glPopMatrix()
def draw_pendulums():
    glColor3f(0.85, 0.85, 0.92)
    for p in pendulums:
        ang = math.sin(elapsed_time * 1.1 + p['phase']) * 40.0
        glPushMatrix()
        glTranslatef(p['x'], p['y'], WALL_H)
        if p['horiz']: glRotatef(ang, 0, 1, 0)
        else: glRotatef(ang, 1, 0, 0)
        glColor3f(0.35, 0.35, 0.4)
        glPushMatrix()
        glScalef(4, 4, 70)
        glTranslatef(0, 0, -0.5)
        glutSolidCube(1.0)
        glPopMatrix()
        glColor3f(0.85, 0.85, 0.92)
        glPushMatrix()
        glTranslatef(0, 0, -75)
        if p['horiz']: glScalef(70, 10, 45)
        else: glScalef(10, 70, 45)
        glutSolidCube(1.0)
        glPopMatrix()
        glPopMatrix()

def get_pendulum_tip(p):
    ang_deg = math.sin(elapsed_time * 1.1 + p['phase']) * 40.0
    ang = math.radians(ang_deg)
    dx = math.sin(ang) * 75.0 if p['horiz'] else 0.0
    dy = 0.0 if p['horiz'] else math.sin(ang) * 75.0
    tip_z = WALL_H - math.cos(ang) * 75.0
    return p['x'] + dx, p['y'] + dy, tip_z
def draw_lasers():
    for l in lasers:
        if l['on']: glColor3f(1.0, 0.15, 0.35)
        elif l.get('warning'):
            pulse = 0.5 + 0.5 * abs(math.sin(elapsed_time * 12.0))
            glColor3f(1.0, 0.85 * pulse + 0.15, 0.1)
        else: continue
        glPushMatrix()
        glTranslatef(l['x'], l['y'], 55)
        if l['horiz']: glScalef(l['length'], 6, 6)
        else: glScalef(6, l['length'], 6)
        glutSolidCube(1.0)
        glPopMatrix()
def draw_spikes():
    for s in spikes:
        raise_amt = 0.0
        if s['state'] == 'up': raise_amt = 55.0
        elif s['state'] == 'rising': raise_amt = 55.0 * min(1.0, s['timer'] / 0.15)
        elif s['state'] == 'lowering': raise_amt = 55.0 * max(0.0, 1.0 - s['timer'] / 0.3)
        glColor3f(0.36, 0.24, 0.14)
        glPushMatrix()
        glTranslatef(s['x'], s['y'], 1)
        glScalef(CELL - 60, CELL - 60, 2)
        glutSolidCube(1.0)
        glPopMatrix()

        if raise_amt > 1 and quadric is not None:
            glColor3f(0.8, 0.8, 0.85)
            for i in range(6):
                ang = (i / 6.0) * 2 * math.pi
                r = 0 if i == 0 else 28
                sx = s['x'] + math.cos(ang) * r
                sy = s['y'] + math.sin(ang) * r
                glPushMatrix()
                glTranslatef(sx, sy, 0)
                gluCylinder(quadric, 6, 0, raise_amt, 8, 4)
                glPopMatrix()

def draw_soldiers():
    bob_base = elapsed_time * 3.0
    for i, s in enumerate(soldiers):
        if not s['alive']: continue
        cfg = SOLDIER_CFG[s['type']]
        flashing = s['hit_flash'] > 0
        base_color = (1.0, 1.0, 1.0) if flashing else cfg['color']

        glPushMatrix()
        glTranslatef(s['x'], s['y'], 0)
        glRotatef(s['facing'], 0, 0, 1)
        walk_swing = math.sin(bob_base + i) * (20.0 if s['state'] == 'combat' else 7.0)
        glColor3f(0.08, 0.07, 0.07)
        for side in (-1, 1):
            glPushMatrix()
            glTranslatef(0, side * 6, 34)
            glRotatef(walk_swing * side, 0, 1, 0)
            glTranslatef(0, 0, -14)
            glScalef(8, 8, 28)
            glutSolidCube(1.0)
            glPopMatrix()

        glColor3f(*base_color)
        glPushMatrix()
        glTranslatef(0, 0, 52)
        glScalef(26, 18, 32)
        glutSolidCube(1.0)
        glPopMatrix()

        if s['type'] == 'assault':
            glColor3f(0.55, 0.55, 0.60)
            glPushMatrix()
            glTranslatef(6, 0, 55)
            glScalef(10, 20, 26)
            glutSolidCube(1.0)
            glPopMatrix()
        if s['type'] == 'shotgun':
            glColor3f(0.10, 0.08, 0.07)
            glPushMatrix()
            glTranslatef(-4, 0, 38)
            glScalef(30, 26, 20)
            glutSolidCube(1.0)
            glPopMatrix()

        glColor3f(0.13, 0.11, 0.11)
        glPushMatrix()
        glTranslatef(0, 0, 78)
        glScalef(15, 15, 15)
        glutSolidCube(1.0)
        glPopMatrix()
        if s['type'] == 'assault':
            glColor3f(0.32, 0.34, 0.30)
            glPushMatrix()
            glTranslatef(0, 0, 87)
            glScalef(17, 17, 7)
            glutSolidCube(1.0)
            glPopMatrix()

        glColor3f(1.0, 0.05, 0.02)
        for side in (-1, 1):
            glPushMatrix()
            glTranslatef(9, side * 4, 80)
            glScalef(3, 3, 3)
            glutSolidCube(1.0)
            glPopMatrix()
        weap_len = {'pistol': 16, 'assault': 34, 'shotgun': 28}[s['type']]
        glColor3f(0.06, 0.06, 0.06)
        glPushMatrix()
        glTranslatef(16, -10, 52)
        glScalef(weap_len, 4, 4)
        glutSolidCube(1.0)
        glPopMatrix()

        glPopMatrix()

def draw_bullets():
    for b in bullets:
        glColor3f(1.0, 0.95, 0.4) if b['owner'] == 'player' else glColor3f(1.0, 0.35, 0.15)
        glPushMatrix()
        glTranslatef(b['x'], b['y'], b['z'])
        glScalef(6, 6, 6)
        glutSolidCube(1.0)
        glPopMatrix()
        glBegin(GL_LINES)
        glVertex3f(b['x'], b['y'], b['z'])
        glVertex3f(b['x'] - b['dx'] * 22, b['y'] - b['dy'] * 22, b['z'])
        glEnd()
def draw_grenades():
    for g in grenades:
        glColor3f(0.15, 0.32, 0.15)
        glPushMatrix()
        glTranslatef(g['x'], g['y'], g['z'])
        if quadric is not None: gluSphere(quadric, 10, 8, 8)
        else:
            glScalef(16, 16, 16)
            glutSolidCube(1.0)
        glPopMatrix()
def draw_explosions():
    for e in explosions:
        t = e['timer'] / 0.4
        r = 20 + t * 75
        glColor3f(1.0, 0.65 * (1 - t) + 0.15, 0.08)
        glPushMatrix()
        glTranslatef(e['x'], e['y'], e['z'])
        if quadric is not None: gluSphere(quadric, r, 10, 10)
        else:
            glScalef(r, r, r)
            glutSolidCube(1.0)
        glPopMatrix()
def draw_player_gun():
    if camera_mode != 'FPV': return
    rad = math.radians(player_angle)
    fwd_x, fwd_y = math.cos(rad), math.sin(rad)
    right_x, right_y = math.cos(rad - math.pi / 2), math.sin(rad - math.pi / 2)

    recoil = (player_fire_cooldown / PLAYER_FIRE_RATE) * 10.0 if player_fire_cooldown > 0 else 0.0
    base_x = player_x + fwd_x * (26 - recoil) + right_x * 11
    base_y = player_y + fwd_y * (26 - recoil) + right_y * 11
    base_z = EYE_Z - 14
    glPushMatrix()
    glTranslatef(base_x, base_y, base_z)
    glRotatef(player_angle, 0, 0, 1)

    glColor3f(0.12, 0.12, 0.12)
    glPushMatrix()
    glScalef(22, 6, 6)
    glutSolidCube(1.0)
    glPopMatrix()
    glPopMatrix()
def draw_player_marker():
    walking = (elapsed_time - last_move_time) < 0.3
    bob = abs(math.sin(elapsed_time * 11.0)) * 4.0 if walking else 0.0
    glPushMatrix()
    glTranslatef(player_x, player_y, 25 + bob)
    glRotatef(player_angle, 0, 0, 1)

    glColor3f(1.0, 0.55, 0.15)
    glPushMatrix()
    glScalef(24, 16, 34)
    glutSolidCube(1.0)
    glPopMatrix()

    glColor3f(1.0, 0.78, 0.45)
    glPushMatrix()
    glTranslatef(0, 0, 26)
    glScalef(16, 16, 16)
    glutSolidCube(1.0)
    glPopMatrix()

    glPopMatrix()
def draw_shapes():
    draw_floor_and_ceiling()
    draw_walls()
    draw_door()
    draw_gems()
    draw_keys()
    draw_pendulums()
    draw_lasers()
    draw_spikes()
    draw_soldiers()
    draw_bullets()
    draw_grenades()
    draw_explosions()
    if camera_mode == 'TOP':
        draw_player_marker()
    draw_player_gun()
def draw_minimap():
    n = MAZE_N
    box_left, box_bottom, box_size = 740, 540, 240

    glMatrixMode(GL_PROJECTION)
    glPushMatrix()
    glLoadIdentity()
    # Near Plane: -1.0, Far Plane: 1.0
    glOrtho(0, 1000, 0, 800, -1.0, 1.0)

    glMatrixMode(GL_MODELVIEW)
    glPushMatrix()
    glLoadIdentity()

    z = -0.999

    # 1. Minimap Base Box
    glColor3f(0.06, 0.06, 0.12)
    glBegin(GL_QUADS)
    glVertex3f(box_left, box_bottom, z)
    glVertex3f(box_left + box_size, box_bottom, z)
    glVertex3f(box_left + box_size, box_bottom + box_size, z)
    glVertex3f(box_left, box_bottom + box_size, z)
    glEnd()

    # Border Line
    glColor3f(0.0, 1.0, 0.4)
    glLineWidth(3.0)
    glBegin(GL_LINE_LOOP)
    glVertex3f(box_left, box_bottom, z)
    glVertex3f(box_left + box_size, box_bottom, z)
    glVertex3f(box_left + box_size, box_bottom + box_size, z)
    glVertex3f(box_left, box_bottom + box_size, z)
    glEnd()

    def to_map(wx, wy):
        mx = box_left + ((wx + CELL / 2.0) / (n * CELL)) * box_size
        my = box_bottom + ((wy + CELL / 2.0) / (n * CELL)) * box_size
        return mx, my

    # 2. Draw Maze Walls on Minimap
    glColor3f(0.2, 0.8, 0.3)
    glLineWidth(2.5)
    glBegin(GL_LINES)
    for (wx, wy, axis) in wall_list:
        if axis == 'X':
            x1, y1 = to_map(wx - CELL / 2.0, wy)
            x2, y2 = to_map(wx + CELL / 2.0, wy)
        else:
            x1, y1 = to_map(wx, wy - CELL / 2.0)
            x2, y2 = to_map(wx, wy + CELL / 2.0)
        glVertex3f(x1, y1, z)
        glVertex3f(x2, y2, z)
    glEnd()

    # 3. Draw Exit Door
    dx, dy = to_map(door_x, door_y)
    if door_open:
        glColor3f(0.0, 1.0, 0.0)
    else:
        glColor3f(1.0, 0.0, 0.0)
    glPointSize(10.0)
    glBegin(GL_POINTS)
    glVertex3f(dx, dy, z)
    glEnd()

    # 4. Draw Player Position & Direction
    px, py = to_map(player_x, player_y)

    # Player Dot
    glColor3f(1.0, 1.0, 1.0)
    glPointSize(8.0)
    glBegin(GL_POINTS)
    glVertex3f(px, py, z)
    glEnd()

    # Facing Line
    rad = math.radians(player_angle)
    dir_x = px + math.cos(rad) * 16
    dir_y = py + math.sin(rad) * 16
    glColor3f(1.0, 0.9, 0.0)
    glLineWidth(2.0)
    glBegin(GL_LINES)
    glVertex3f(px, py, z)
    glVertex3f(dir_x, dir_y, z)
    glEnd()

    glPopMatrix()
    glMatrixMode(GL_PROJECTION)
    glPopMatrix()
    glMatrixMode(GL_MODELVIEW)

def compass_hint():
    dx, dy = door_x - player_x, door_y - player_y
    dist = math.hypot(dx, dy)
    angle_to_door = math.degrees(math.atan2(dy, dx))
    rel = (angle_to_door - player_angle + 180) % 360 - 180
    if abs(rel) < 25: arrow = "AHEAD ^"
    elif abs(rel) > 155: arrow = "BEHIND v"
    elif rel > 0: arrow = "LEFT <"
    else: arrow = "RIGHT >"
    return "EXIT: {}  ({} units)".format(arrow, int(dist))

def draw_hud():
    draw_text(10, 770, "HEALTH: {}".format(int(max(0, player_health))))
    mm = int(max(0, time_left) // 60)
    ss = int(max(0, time_left) % 60)
    draw_text(10, 745, "TIME LEFT: {:02d}:{:02d}".format(mm, ss))
    draw_text(10, 720, "GEMS: {} / {}".format(gems_collected, len(gems)))
    draw_text(10, 695, "KEYS: {} / {}".format(keys_collected, TOTAL_KEYS))
    draw_text(10, 670, "SCORE: {}".format(score))
    draw_text(10, 620, "CAMERA: {}   GOD MODE: {}".format("TOP-DOWN" if camera_mode == 'TOP' else "FIRST-PERSON", "ON" if god_mode else "off"))
    draw_text(10, 595, compass_hint())
    draw_text(10, 30, "W/S move  A/D turn  LEFT-CLICK shoot  V view (FPV/TOP)  C god mode  R reset")
    if game_state == 'won':
        draw_text(370, 420, "YOU ESCAPED THE MAZE!", GLUT_BITMAP_TIMES_ROMAN_24)
        draw_text(370, 390, "Final score: {}   Press R to play again".format(score))
    elif game_state == 'lost':
        draw_text(370, 420, "MAZE CLAIMED YOU", GLUT_BITMAP_TIMES_ROMAN_24)
        draw_text(370, 390, "Final score: {}   Press R to play again".format(score))

def update_pickups():
    global gems_collected, score, combo_count, combo_timer, keys_collected
    if combo_timer > 0:
        combo_timer -= 1.0 / 60.0
        if combo_timer <= 0: combo_count = 0
    for g in gems:
        if not g['alive']: continue
        if circle_hit(player_x, player_y, g['x'], g['y'], 34):
            g['alive'] = False
            gems_collected += 1
            combo_count += 1
            combo_timer = COMBO_WINDOW
            score += 10 * min(combo_count, 5)

    for k in keys_list:
        if not k['alive']: continue
        if circle_hit(player_x, player_y, k['x'], k['y'], 34):
            k['alive'] = False
            keys_collected += 1
            score += 75

def update_door():
    global door_open
    if keys_collected >= TOTAL_KEYS and not door_open:
        door_open = True

def update_pendulums():
    for p in pendulums:
        tx, ty, tz = get_pendulum_tip(p)
        if tz < 90 and circle_hit(player_x, player_y, tx, ty, 45):
            damage_player(15)

def update_lasers(dt):
    for l in lasers:
        l['timer'] += dt
        if l['on']:
            if l['timer'] > l['on_duration']:
                l['timer'] = 0.0
                l['on'] = False
        else:
            if l['timer'] > l['off_duration']:
                l['timer'] = 0.0
                l['on'] = True

        l['warning'] = (not l['on']) and (l['timer'] > l['off_duration'] - 0.7)

        if l['on']:
            hit = (abs(player_y - l['y']) < 25 and abs(player_x - l['x']) < l['length'] / 2.0) if l['horiz'] else (abs(player_x - l['x']) < 25 and abs(player_y - l['y']) < l['length'] / 2.0)
            if hit: damage_player(8)


def update_spikes(dt):
    for s in spikes:
        near = circle_hit(player_x, player_y, s['x'], s['y'], 45)
        if s['state'] == 'idle' and near:
            s['state'] = 'rising'; s['timer'] = 0.0
        elif s['state'] == 'rising':
            s['timer'] += dt
            if s['timer'] > 0.15: s['state'] = 'up'; s['timer'] = 0.0
        elif s['state'] == 'up':
            s['timer'] += dt
            if near: damage_player(0.4)
            if s['timer'] > 1.0: s['state'] = 'lowering'; s['timer'] = 0.0
        elif s['state'] == 'lowering':
            s['timer'] += dt
            if s['timer'] > 0.3: s['state'] = 'cooldown'; s['timer'] = 0.0
        elif s['state'] == 'cooldown':
            s['timer'] += dt
            if s['timer'] > 1.0 and not near: s['state'] = 'idle'
def fire_soldier_weapon(s):
    cfg = SOLDIER_CFG[s['type']]
    rad = math.radians(s['facing'])
    muzzle_x = s['x'] + math.cos(rad) * 26
    muzzle_y = s['y'] + math.sin(rad) * 26

    if s['type'] == 'shotgun':
        s['shots_fired'] += 1
        s['fire_timer'] = cfg['fire_rate'] * random.uniform(0.85, 1.2)
        if s['shots_fired'] % 4 == 0:
            grenades.append({'x': s['x'], 'y': s['y'], 'z': 55, 'start_x': s['x'], 'start_y': s['y'], 'target_x': player_x, 'target_y': player_y, 'timer': 0.0, 'flight_time': GRENADE_FLIGHT_TIME, 'fuse': GRENADE_FUSE})
            return
        for spread_deg in (-10, -4, 0, 4, 10):
            a = rad + math.radians(spread_deg)
            bullets.append({'x': muzzle_x, 'y': muzzle_y, 'z': 55, 'dx': math.cos(a), 'dy': math.sin(a), 'speed': 700.0, 'life': 0.55, 'owner': 'enemy', 'damage': cfg['damage']})
    else:
        s['fire_timer'] = cfg['fire_rate'] * random.uniform(0.85, 1.25)
        jitter = math.radians(random.uniform(-4, 4))
        a = rad + jitter
        bullets.append({'x': muzzle_x, 'y': muzzle_y, 'z': 55, 'dx': math.cos(a), 'dy': math.sin(a), 'speed': 800.0, 'life': BULLET_LIFE, 'owner': 'enemy', 'damage': cfg['damage']})
def update_soldiers(dt):
    global danger_flash
    closest_combat = None

    for s in soldiers:
        if not s['alive']: continue
        if s['hit_flash'] > 0: s['hit_flash'] -= dt

        s['detect_timer'] -= dt
        if s['detect_timer'] <= 0:
            s['detect_timer'] = 0.25
            dist_check = math.hypot(player_x - s['x'], player_y - s['y'])
            if dist_check < SOLDIER_DETECT_RANGE and has_line_of_sight(s['x'], s['y'], player_x, player_y):
                s['state'] = 'combat'
            elif dist_check > SOLDIER_DETECT_RANGE * 1.4:
                s['state'] = 'patrol'

        if s['state'] == 'combat':
            dx, dy = player_x - s['x'], player_y - s['y']
            dist = math.hypot(dx, dy) or 0.0001
            target_ang = math.degrees(math.atan2(dy, dx))
            s['facing'] = target_ang

            if dist < SOLDIER_DETECT_RANGE:
                closest_combat = dist if closest_combat is None else min(closest_combat, dist)

            s['strafe_timer'] -= dt
            if s['strafe_timer'] <= 0:
                s['strafe_timer'] = random.uniform(0.8, 1.6)
                s['strafe_dir'] *= -1
            perp = math.radians(target_ang + 90.0)
            mvx = math.cos(perp) * s['strafe_dir']
            mvy = math.sin(perp) * s['strafe_dir']
            fwd = math.radians(target_ang)
            if dist < 180.0:
                mvx -= math.cos(fwd) * 0.6
                mvy -= math.sin(fwd) * 0.6
            elif dist > 260.0:
                mvx += math.cos(fwd) * 0.6
                mvy += math.sin(fwd) * 0.6

            norm = math.hypot(mvx, mvy) or 1.0
            spd = SOLDIER_MOVE_SPEED * dt
            nx, ny = resolve_entity_collision(s['x'] + (mvx / norm) * spd, s['y'] + (mvy / norm) * spd, 22)
            s['x'], s['y'] = nx, ny

            s['fire_timer'] -= dt
            if s['fire_timer'] <= 0 and has_line_of_sight(s['x'], s['y'], player_x, player_y):
                fire_soldier_weapon(s)
        else:
            if len(s['path']) > 1:
                tx, ty = s['path'][s['idx']]
                ddx, ddy = tx - s['x'], ty - s['y']
                d = math.hypot(ddx, ddy)
                if d < 6:
                    s['idx'] = (s['idx'] + 1) % len(s['path'])
                else:
                    spd = 45.0 * dt
                    s['x'] += (ddx / d) * spd
                    s['y'] += (ddy / d) * spd
                    s['facing'] = math.degrees(math.atan2(ddy, ddx))

        if circle_hit(player_x, player_y, s['x'], s['y'], SOLDIER_MELEE_RANGE):
            damage_player(4)

    danger_flash = (not god_mode) and ((closest_combat is not None and closest_combat < 260) or player_health <= 35)

def update_bullets(dt):
    global score
    for b in bullets[:]:
        b['life'] -= dt
        if b['life'] <= 0:
            bullets.remove(b)
            continue
        step = b['speed'] * dt
        nx = b['x'] + b['dx'] * step
        ny = b['y'] + b['dy'] * step

        blocked = False
        for (minx, maxx, miny, maxy) in wall_boxes:
            if minx <= nx <= maxx and miny <= ny <= maxy:
                blocked = True; break
        if blocked:
            bullets.remove(b)
            continue
        b['x'], b['y'] = nx, ny

        if b['owner'] == 'player':
            for s in soldiers:
                if not s['alive']: continue
                if circle_hit(nx, ny, s['x'], s['y'], 24):
                    s['hp'] -= b['damage']
                    s['hit_flash'] = 0.15
                    if s['hp'] <= 0:
                        s['alive'] = False
                        score += SOLDIER_CFG[s['type']]['score']
                    bullets.remove(b)
                    break
        else:
            if circle_hit(nx, ny, player_x, player_y, PLAYER_R):
                damage_player(b['damage'])
                bullets.remove(b)
def update_grenades(dt):
    for g in grenades[:]:
        if g['timer'] < g['flight_time']:
            g['timer'] += dt
            t = min(1.0, g['timer'] / g['flight_time'])
            g['x'] = g['start_x'] + (g['target_x'] - g['start_x']) * t
            g['y'] = g['start_y'] + (g['target_y'] - g['start_y']) * t
            g['z'] = 55 + math.sin(t * math.pi) * 65
        else:
            g['fuse'] -= dt
            if g['fuse'] <= 0:
                dist = math.hypot(player_x - g['x'], player_y - g['y'])
                if dist < GRENADE_RADIUS:
                    falloff = 1.0 - (dist / GRENADE_RADIUS) * 0.5
                    damage_player(GRENADE_DAMAGE * falloff)
                explosions.append({'x': g['x'], 'y': g['y'], 'z': g['z'], 'timer': 0.0})
                grenades.remove(g)
def update_explosions(dt):
    for e in explosions[:]:
        e['timer'] += dt
        if e['timer'] > 0.4: explosions.remove(e)

def check_exit():
    global game_state
    if door_open and circle_hit(player_x, player_y, door_x, door_y + 40, 60):
        game_state = 'won'
def game_tick():
    global last_tick, elapsed_time, time_left, hit_cooldown, game_state, player_fire_cooldown

    now = time.time()
    dt = min(now - last_tick if last_tick else 0.0, 0.05)
    last_tick = now
    elapsed_time += dt

    if game_state != 'playing': return
    time_left -= dt
    if time_left <= 0:
        time_left = 0
        game_state = 'lost'
        return
    if hit_cooldown > 0: hit_cooldown -= dt
    if player_fire_cooldown > 0: player_fire_cooldown -= dt
    update_pickups()
    update_door()
    update_pendulums()
    update_lasers(dt)
    update_spikes(dt)
    update_soldiers(dt)
    update_bullets(dt)
    update_grenades(dt)
    update_explosions(dt)
    check_exit()

#  INPUT & CAMERA
def keyboardListener(key, x, y):
    global player_x, player_y, player_angle, camera_mode, god_mode, last_move_time
    if game_state == 'playing':
        if key == b'w':
            rad = math.radians(player_angle)
            nx = player_x + math.cos(rad) * PLAYER_SPEED
            ny = player_y + math.sin(rad) * PLAYER_SPEED
            player_x, player_y = resolve_collision(nx, ny)
            last_move_time = elapsed_time
        if key == b's':
            rad = math.radians(player_angle)
            nx = player_x - math.cos(rad) * PLAYER_SPEED
            ny = player_y - math.sin(rad) * PLAYER_SPEED
            player_x, player_y = resolve_collision(nx, ny)
            last_move_time = elapsed_time

        if key == b'a': player_angle = (player_angle + TURN_STEP) % 360
        if key == b'd': player_angle = (player_angle - TURN_STEP) % 360

    if key == b'c': god_mode = not god_mode
    if key == b'v': camera_mode = 'TOP' if camera_mode == 'FPV' else 'FPV'
    if key == b'r': init_game()
    glutPostRedisplay()

def mouseListener(button, state, x, y):
    global player_fire_cooldown
    if button == GLUT_LEFT_BUTTON and state == GLUT_DOWN:
        if game_state == 'playing' and player_fire_cooldown <= 0:
            rad = math.radians(player_angle)
            bullets.append({
                'x': player_x + math.cos(rad) * 30, 'y': player_y + math.sin(rad) * 30, 'z': EYE_Z,
                'dx': math.cos(rad), 'dy': math.sin(rad),
                'speed': BULLET_SPEED, 'life': BULLET_LIFE,
                'owner': 'player', 'damage': 1,
            })
            player_fire_cooldown = PLAYER_FIRE_RATE
    glutPostRedisplay()

def setupCamera():
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    gluPerspective(fovY, 1.25, 0.1, 4000)
    glMatrixMode(GL_MODELVIEW)
    glLoadIdentity()
    if camera_mode == 'FPV':
        rad = math.radians(player_angle)
        eye_x, eye_y, eye_z = player_x, player_y, EYE_Z
        look_x = player_x + math.cos(rad) * 50
        look_y = player_y + math.sin(rad) * 50
        gluLookAt(eye_x, eye_y, eye_z, look_x, look_y, EYE_Z, 0, 0, 1)
    else:
        # Overhead Top View
        center_x = (MAZE_N * CELL) / 2.0 - (CELL / 2.0)
        center_y = (MAZE_N * CELL) / 2.0 - (CELL / 2.0)
        cam_height = MAZE_N * CELL * 1.3
        gluLookAt(center_x, center_y - 1, cam_height, center_x, center_y, 0, 0, 0, 1)

def ensure_started():
    global quadric, _started
    if _started: return
    glEnable(GL_DEPTH_TEST)
    glClearColor(0.65, 0.85, 0.96, 1.0)
    quadric = gluNewQuadric()
    _started = True

def idle():
    ensure_started()
    game_tick()
    glutPostRedisplay()

def showScreen():
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    setupCamera()
    draw_shapes()
    draw_minimap()
    draw_hud()
    glutSwapBuffers()
def main():
    glutInit()
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH)
    glutInitWindowSize(1000, 800)
    glutInitWindowPosition(0, 0)
    glutCreateWindow(b"3D OpenGL Intro - Maze Game")

    glutDisplayFunc(showScreen)
    glutKeyboardFunc(keyboardListener)
    glutMouseFunc(mouseListener)
    glutIdleFunc(idle)
    glutMainLoop()

init_game()
if __name__ == "__main__":
    main()
